// Code generated by mockery v2.9.4. DO NOT EDIT.

package programming

import mock "github.com/stretchr/testify/mock"

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// NewUUID provides a mock function with given fields: withtoutHyphens
func (_m *MockInterface) NewUUID(withtoutHyphens bool) string {
	ret := _m.Called(withtoutHyphens)

	var r0 string
	if rf, ok := ret.Get(0).(func(bool) string); ok {
		r0 = rf(withtoutHyphens)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
